FROM alpine:3.7
MAINTAINER Stephanie Kuhne <stephanie.kuhne@ge.com>

RUN set -ex \
	&& apk add --no-cache \
		bash \
		make \
		g++ \
		python \
		git \ 
	# need this for alpine musl libc
	&& ln -sf /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2 
RUN apk add --update nodejs nodejs-npm

EXPOSE 8080
